name: CI - release main.pdf
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: main.typ

      - name: Rename output
        run: cp main.pdf requin.pdf

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: requin.pdf
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }}"
          files: requin.pdf
